os:
  - osx
language: swift
sudo: required
osx_image: xcode10.3
script:
  - set -o pipefail
  - xcodebuild -project NetworkSugarExample.xcodeproj -scheme "NetworkSugarExample"  -sdk iphonesimulator  -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' test
notifications:
  email:
    on_success: never
    on_failure: change
